name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"

jobs:

  regressions:

    strategy:
      matrix:
        repo:
        - arogozhnikov/einops
        - abhiTronix/vidgear
        - jmoiron/humanize
        - cgarciae/pypeln
        - cgarciae/pypeln
        - salesforce/policy_sentry
        - archivy/archivy
        - giswqs/geemap
        - salesforce/cloudsplaining
        - deepcharles/ruptures
        - DataDog/integrations-core
        - MaartenGr/BERTopic
        - damiafuentes/DJITelloPy
        - damiafuentes/DJITelloPy
        - pawamoy/mkdocstrings
        - koaning/human-learn
        - MaartenGr/KeyBERT
        - MaartenGr/PolyFuzz
        - RasaHQ/whatlies
        - pawamoy/aria2p
        - copier-org/copier
        - poets-ai/elegy
        - cs01/pygdbmi
        - TheHive-Project/TheHive4py
        - sleuth-io/code-video-generator
        - aparcar/asu
        - kelvindecosta/picharsso
        - pawamoy/shell-history
        - daxartio/tinvest
        - suned/pfun
        - coady/multimethod
        - hSaria/ChromaTerm
        - basedosdados/mais
        - pyomeca/pyomeca
        - abdullahselek/HerePy
        - koaning/clumper
        - Servir-Mekong/hydra-floods
        - coady/django-model-values
        - phurwicz/hover
        - abdullahselek/authenticatorpy
        - JosXa/tgintegration
        - up42/up42-py
        - voidful/TFkit
        - tjltjl/plycutter
        - sinaahmadi/klpt
        - 173TECH/sayn
        - pawamoy/git-changelog
        - verifid/facereg
        - abdullahselek/spampy
        - openkinome/kinoml
        - ppsp-team/HyPyP
        - voidful/NLPrep
        - verifid/mocr
        - pawamoy/pytkdocs
        - Skyscanner/pycfmodel
        - abdullahselek/koolsla
        - algobulls/pyalgotrading
        - coady/placeholder
        - cgarciae/dataget
        - voidful/nlp2go
        - deethon/deethon
        - Materials-Consortia/optimade-python-tools
        - microsoft/reconner
        - pawamoy/dependenpy
        - coady/waiter
        - columbia-it/django-jsonapi-training
        - giswqs/eefolium
        - coady/graphique
        - mthorrell/wideboost
        - ing-bank/probatus
        - materialsproject/maggma
        - tshauck/gcgc
        - jrieke/traintool
        - pawamoy/moving-stars
        - pawamoy/archan
        - CostReduce/cli
        - pawamoy/shellman
        - manujosephv/deeprenewalprocess
        - pawamoy/pawabot
        - jvfe/reconciler
        - jvfe/reconciler
        - coady/clients
        - coady/futured
        - PhIMaL/DeePyMoD
        - lyz-code/autoimport
        - lumapps/lumapps-sdk
        - materialsproject/mrnet
        - andreztz/notify-send
        - koaning/memo
        - gergelyk/peepshow
        - openforcefield/qcsubmit
        - pawamoy/duty
        - CapgeminiInventIDE/doc_loader
        - pawamoy/privibot
        - coady/spector
        - pawamoy/failprint
        - pawamoy/ansito
        - robertanto/bob_telegram_tools
        - materialsproject/pyRho
        - cogip/simulation
        - shervinazadi/topoGenesis
        - nsidnev/edgeql-queries
        - pawamoy/neopy
        - aahnik/py_package
        - chenrz925/waterch-tasker
        - rorre/Phillip
        - tjhunter/dds_py
        - auredentan/starlette-session
        - jvfe/wikidata_panglaodb
        - cuenca-mx/facturapi-python
        - mcous/decoy
        - jayqi/quickhttp
        - jnoortheen/arger
        - jvfe/wikidata_panglaodb
        - triaxtec/flex-config
        - felipemarkson/dssdata
        - christian-hawk/pydoautomator
        - frankier/skelshop
        - pedrolarben/ADLStream
        - pawamoy/keycut
        - HumanBrainProject/PyJuGEx
        - PatrickOHara/tspwplib
        - pawamoy/mvodb
        - Brickworks/HAB-toolbox
        - pennz/kaggle_runner
        - peterspackman/chmpy
        - usnistgov/nestor
        - YannBeauxis/sinagot
        - peterspackman/chmpy
        - besmerd/spool
        - fabridamicelli/echoes
        - TensorTom/traversy
        - kabirkhan/recon
        - HSF-reco-and-software-triggers/Tracking-ML-Exa.TrkX
        - ValentinCalomme/syngle
        - jacquelinegarrahan/lume-epics
        - slaclab/lume-model
        - Abd0s/skidtools
        - e2fyi/iotoolz
        - collectif-codata/pyepidemics
        - phil65/PrettyQt
        - avast/ep-stats
        - jacquelinegarrahan/lume-model
        - jejjohnson/rbig_eo
        - nigelm/broadworks_ocip
        - pawamoy/neo4j-api
        - yanniskatsaros/gutensearch
        - shmileee/bitbucket-python-client
        - pawamoy/unminder
        - nigelm/ssh2_parse_key
        - btjanaka/logdir
        - nstockton/mapperproxy-mume
        - aparcar/udronerc
        - simon-engledew/aiosshim
        - cimourdain/piteau
        - gewalt01/emuke-docstrings
        - gergelyk/python-digitout
        - remykusters/DeePyMoD2
        - daxartio/daxartio.github.io
        - joshiswhite19/Hack2020TelloDrone
        - duichwer/mkdocstringsdummy
        - nickc1/seebuoy
        - erp12/performance-curves
        - slaclab/lume-epics
        - Rushyanth111/Semester-Stats-Report
        - mondeja/http-request-codegen
        - joshiswhite19/Hack2020TelloDrone
        - ejolly/utilz
        - na0fu3y/bqformat
        - elementhuman/biometrics-client
        - daxartio/termynal
        - Strategy-Tap/Novizi-BackEnd
        - ASFHyP3/hyp3-sdk
        - Mohamed-Kaizen/IWork-test
        - INSPIDE/pyportall
        - AyrtonB/Octopy-Energy
        - rohit507/exam_gen
        - rkingsbury/membrane-toolkit
        - cutec-chris/halc
        - lyz-code/routine
        - phil65/pandastools
        - DataDog/datadog-api-client-python
        - gergelyk/python-tibidi
        - kabirkhan/dstl
        - cgarciae/dicto
        - lyz-code/trusted-advisor-exporter
        - Onefootball/onefootball-network-api-py
        - cimourdain/estrade
        - tms-studio/python-music-browser
        - kuwv/python-compendium
        - Mohamed-Kaizen/teached
        - cimourdain/python_lib_template
        - gergelyk/python-indentedlogs
        - lyz-code/drode
        - wolfgangwazzlestrauss/scaffold-python
        - Mohamed-Kaizen/ihsan
        - kchennen/PythonProject
        - Mohamed-Kaizen/ethiopian-identity-provider
        - lyz-code/yamlfix
        - wolfgangwazzlestrauss/cloudpath
        - ExpressApp/pybotx
        - romainmartinez/pyomeca-refactor
        - lyz-code/cookiecutter-python-project
        - wolfgangwazzlestrauss/yamltable
        - kuwv/python-argufy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: repos
        key: repo-${{ matrix.repo }}

    - name: Check for regressions
      run: bash build.sh one ${{ matrix.repo }}

    - name: Archive logs
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.repo }}
        path: logs
