name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"

jobs:

  regressions:

    strategy:
      matrix:
        repo:
        - arogozhnikov/einops
        - abhiTronix/vidgear
        - jmoiron/humanize
        - cgarciae/pypeln
        - salesforce/policy_sentry
        - archivy/archivy
        - giswqs/geemap
        - salesforce/cloudsplaining
        - deepcharles/ruptures
        - DataDog/integrations-core
        - MaartenGr/BERTopic
        - damiafuentes/DJITelloPy
        - damiafuentes/DJITelloPy
        - pawamoy/mkdocstrings
        - koaning/human-learn
        - MaartenGr/KeyBERT
        - MaartenGr/PolyFuzz
        - RasaHQ/whatlies
        - pawamoy/aria2p
        - copier-org/copier
        - poets-ai/elegy
        - cs01/pygdbmi
        - TheHive-Project/TheHive4py
        - sleuth-io/code-video-generator
        - aparcar/asu
        - kelvindecosta/picharsso
        - pawamoy/shell-history
        - daxartio/tinvest
        - suned/pfun
        - coady/multimethod
        - hSaria/ChromaTerm
        - basedosdados/mais
        - pyomeca/pyomeca
        - abdullahselek/HerePy
        - koaning/clumper
        - Servir-Mekong/hydra-floods
        - coady/django-model-values
        - phurwicz/hover
        - abdullahselek/authenticatorpy
        - JosXa/tgintegration
        - up42/up42-py
        - voidful/TFkit
        - tjltjl/plycutter
        - sinaahmadi/klpt
        - 173TECH/sayn
        - pawamoy/git-changelog
        - verifid/facereg
        - abdullahselek/spampy
        - openkinome/kinoml
        - ppsp-team/HyPyP

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install PyYAML
      run: python -m pip install --user pyyaml

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: repos
        key: repo-${{ matrix.repo }}

    - name: Check for regressions
      run: bash build.sh one ${{ matrix.repo }}
