name: Regressions

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      to_upgrade:
        description: 'The dependency to upgrade and compare: repository@branch'
        required: true
        default: 'git+https://github.com/mkdocs/mkdocs.git@master'

jobs:
  regressions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - crystal-lang/crystal-book
          - e-maxx-eng/e-maxx-eng
          - emacs-lsp/lsp-mode
          - gledos/ggame
          - ikrima/gamedevguide
          - k3d-io/k3d
          - librenms/librenms
          - mkdocs/mkdocs
          - mkdocstrings/mkdocstrings
          - nasa-jpl/open-source-rover
          - Noovolari/leapp
          - ni/systemlink-operations-handbook
          - ntno/mkdocs-terminal
          - open-amt-cloud-toolkit/docs
          - oprypin/mkdocs-gen-files
          - Rat-Rig/V-core-3
          - seleniumbase/SeleniumBase
          - spaceship-prompt/spaceship-prompt
          - tfeldmann/organize
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Setup
      run: ./build.sh setup ${{ matrix.repo }}
    - name: Build current version
      run: ./build.sh build_current ${{ matrix.repo }}
    - name: Build latest version
      run: ./build.sh build_latest ${{ matrix.repo }} ${{ github.event.inputs.to_upgrade }}
    - name: Compare sites
      run: ./build.sh compare ${{ matrix.repo }}
