name: ci

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"

jobs:

  regressions:

    strategy:
      fail-fast: false
      matrix:
        repo:
          - crystal-lang/crystal-book
          - e-maxx-eng/e-maxx-eng
          - emacs-lsp/lsp-mode
          - gledos/ggame
          - ikrima/gamedevguide
          - k3d-io/k3d
          - librenms/librenms
          - ManticoreGamesInc/platform-documentation
          - ni/systemlink-operations-handbook
          - open-amt-cloud-toolkit/docs
          - oprypin/mkdocs-gen-files
          - Rat-Rig/V-core-3
          - seleniumbase/SeleniumBase
          - spaceship-prompt/spaceship-prompt
          - tfeldmann/organize


    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install -U pip wheel pyyaml beautifulsoup4 ${{ matrix.deps }}

    #- name: Set up the cache
    #  uses: actions/cache@v1
    #  with:
    #    path: repos
    #    key: repo-${{ matrix.repo }}

    - name: Build current version
      id: build_current
      run: bash build.sh one_current ${{ matrix.repo }}

    - name: Build latest version
      run: bash build.sh one_latest ${{ matrix.repo }}
