name: ci

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"

jobs:

  regressions:

    strategy:
      fail-fast: false
      matrix:
        repo:
        - arogozhnikov/einops
        - jmoiron/humanize
        #- cgarciae/pypeln
        - salesforce/policy_sentry
        - archivy/archivy
        - giswqs/geemap
        - salesforce/cloudsplaining
        #- deepcharles/ruptures
        #- DataDog/integrations-core
        - damiafuentes/DJITelloPy
        - MaartenGr/PolyFuzz
        #- pawamoy/mkdocstrings
        #- koaning/human-learn
        #- RasaHQ/whatlies
        #- pawamoy/aria2p
        - copier-org/copier
        - poets-ai/elegy
        - TheHive-Project/TheHive4py
        # - sleuth-io/code-video-generator
        - aparcar/asu
        #- kelvindecosta/picharsso
        - daxartio/tinvest
        #- tjltjl/plycutter
        - PySport/kloppy
        #- pawamoy/shell-history
        #- coady/multimethod
        # - hSaria/ChromaTerm
        - basedosdados/mais
        #- pyomeca/pyomeca
        - abdullahselek/HerePy
        - Servir-Mekong/hydra-floods
        - JosXa/tgintegration
        - koaning/clumper
        #- coady/lupyne
        #- RasaHQ/rasa-nlu-examples
        - abdullahselek/authenticatorpy
        - coady/django-model-values
        #- DigitalPhonetics/adviser
        - up42/up42-py
        #- beancount/docs
        - 173TECH/sayn
        #- zmbc/shakespearelang
        #- sinaahmadi/klpt
        - pawamoy/git-changelog
        #- verifid/facereg
        - abdullahselek/spampy
        #- ppsp-team/HyPyP
        - lyz-code/blue-book
        #- openkinome/kinoml
        - voidful/NLPrep
        - abdullahselek/koolsla
        - pawamoy/pytkdocs
        - verifid/mocr
        #- Skyscanner/pycfmodel
        - algobulls/pyalgotrading

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install PyYAML
      run: python -m pip install --user pyyaml beautifulsoup4

    #- name: Set up the cache
    #  uses: actions/cache@v1
    #  with:
    #    path: repos
    #    key: repo-${{ matrix.repo }}

    - name: Build current version
      id: build_current
      run: bash build.sh one_current ${{ matrix.repo }}

    - name: Build latest version
      run: bash build.sh one_latest ${{ matrix.repo }}
